dist: bionic
language: java
jdk: openjdk11
before_install:
- sudo apt-get -y install libpng16-16 libwebkitgtk-1.0-0 zlib1g-dev libc6-dev libstdc++6
- sudo apt-get -y install python3-pip python3-dev
- DEBIAN_FRONTEND=noninteractive sudo apt-get -y install xorg xserver-xorg-video-dummy
- sudo -H pip3 install -U setuptools
- sudo -H pip3 install -U wheel
install:
- pip3 install gdown
- pip3 install mbpkg
script:
- "./travis.sh"
deploy:
  provider: releases
  api_key:
    secure: TfOsW35V0HH/qEbKzKEn1Y+sX9vuMbW6bhKKji64y4Uegk2y63rcNPDUmoWzhnDOXk3zbUtleYTDawj3m+gYSDZe5RnSCZDbMH/yLrnbRH61i/zGKoZgxjGf3NphoXx5bW7C1d8mQZqxMjSMJ4nuPfLGpOpeCfk4FI8A6cyU33cJ8VxO4ZebSMxICuhc0x5kQdskPDaTn32/JzAC+80veOsFNErp1NAR4n8X6DELSVurjCF7d3Z57mVicFdU8i40XTxi3nJrZEBy400EU2InQHRkwofsDh7vex0Dn9aTcPnFPQnEdE1n1AR1UMhZi0fEqoxYe8OXR2McnUr/APbGjT1w2tlFBn7yR285Za56hFZqTtvOq6NgdilIoV7Bavdn7E6VqvyJTFfvNBApfMR2c5xSj3OR/ienzqiVI6MKJZ2QlMUvRSm58sKaZecp5Lg98hV8hgQUoIC5nxQ3PglcIO1y8pnRPbceQ073fR3W61qvIejW7oSKcTof/ORcoJ/aZCkyqxmmo5pjmZtfX4o9ZsVPUUKnMfE9ALprGfsRpQVc92hVOnqo0pBS32ZU1aI2gJotSbm/evLHO3D5PRGCZNk8WxithrD5d+ZNT9jPJs/DwfbXRFd1nq67eeQdZ6k9zp9kNUDI607+wOYLww/mESW+CHF/Xb+erE3LuX5HFzE=
  file_glob: true
  file: "bin/*.barrel"
  skip_cleanup: true
  draft: true
  on:
    tags: true
after_deploy:
  - npm install -g github-release-notes
  - gren release --token ${GH_TOKEN} --tags $(git describe)
