language: java
jdk: openjdk11
script:
- "./travis.sh"
deploy:
  provider: releases
  api_key:
    secure: BlOvcKMlbMrlcJzoA1vNjQDJR22Xsl20fG8sGH7L4NVtSnyCUjWCfTtrbDz6KXA6x+dVRAfOwORIG3quNR9xU7oJu2P1jisVzkw90kHakNPIZWxGSl4OTQrwZfdFd9gCuNpEY3LPrPSN+1I0HZXbXWlwiiBCcUMjz2qFVnunqiRu5Onvp9sa431b7LQ+VwN7+/D41DDsSDXU1rK1+hslEPS6oljx2MueZ23eX5x2dnpL8+DCQokKowW2HxcNIBwC6En86UFUpllvTduvLsvVaJa/eZY3LFGMnlhhUIIwlmNXhO5697N3j6NdRlNMH+Dn2XDSSZMy12SCuApnrxY+D4acS+9eawUJXPcf4PdgDrXFI/AWkjv44YomuXE/CvA1BkzZDCGiKPuKliCAvTz60CA19EdAZZamUWb5OtVNeou4XVgTZ1NGY8QwLRNEL/CMV9hLfjax3x0DaH3S7RGWsrBwO8AMJMhJ7p3lpV1oiuNvwm+qU5cfh97VRLhLmVvlkUUEpTtIzHPFpmRXqVWPY2GBFATPj4ZN7CFxHAD2MBKEJlpuf0OWzOcwkEZOLFOqOeV8sPomi2u7RC8KUI/fLdPlpAN1gSn46vFwwA0iDdOg/9zY/6UTC5WgVEEpvmp110Zw83Q5nbgEuYAX4GK8e6ifRk3N5uYkGSaF75VQ+tw=
  file_glob: true
  file: "bin/*.barrel"
  skip_cleanup: true
  draft: true
  on:
    tags: true
